apiVersion: v1
kind: Pod
metadata:
  name: my-pod-alba
spec:
  containers:
    - name: my-main-container
      image: alpine
      command: ["sleep", "infinity"] 
      env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
    - name: dind
      image: docker:dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
  volumes:
    - name: dind-storage
      emptyDir: {}